- name: variables from prompt
  hosts: localhost
  vars_prompt: 
  - name: USERNAME
    prompt: Please enter your username
    private: false
  - name: PASSWORD
    prompt: Please enter your password
    private: true
  tasks: 
  - name: print informtion
    ansible.builtin.debug:
      msg: "Hi, Username is: {{USERNAME}} and Password is: {{PASSWORD}}"