- name: variable reference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAY variable"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    promt: please enter wishes
    private: false
  tasks: 
  - name: check preference
    vars:
      WISHES: "Morning from TASK variable"
    ansible.builtin.debug:
      msg: "Hello, good {{WISHES}}"